name: SafetyWorldEdit
version: '1.1'
main: net.harupiza.safetyWorldEdit.SafetyWorldEdit
api-version: '1.20'
authors: [ pizzaharumaki ]
website: https://github.com/fhrk-78

permissions:
  safetyWorldEdit.skipSafetyCheck:
    default: false
    description: Skip WorldEdit safety check
